In [107]:
import pandas as pd

In [108]:
df = pd.read_csv("C:/Users/Teoh Teik Teo/OneDrive - TSS Global Pte. Ltd/TT Library/AI Model/Data/CyberSecurity.csv")

In [109]:
print(df)

        FIT101    LIT101   MV101  P101  P102    AIT201    AIT202    AIT203  \
0     2.427057  522.8467       2     2     1  262.0161  8.396437  328.6337   
1     2.446274  522.8860       2     2     1  262.0161  8.396437  328.6337   
2     2.489191  522.8467       2     2     1  262.0161  8.394514  328.6337   
3     2.534350  522.9645       2     2     1  262.0161  8.394514  328.6337   
4     2.569260  523.4748       2     2     1  262.0161  8.394514  328.6337   
...        ...       ...     ...   ...   ...       ...       ...       ...   
9995  0.000000  810.6872       1     1     1  263.5222  8.439375  316.7906   
9996  0.000000  810.6479       1     1     1  263.5222  8.439375  316.7906   
9997  0.000000  810.8442       1     1     1  263.5222  8.439375  316.7906   
9998  0.000000  811.0012       1     1     1  263.5222  8.439375  316.7906   
9999  0.000000  810.6872       1     1     1  263.5222  8.439375  316.7906   

        FIT201  Attack  
0     2.445391       0  
1     2.44539

In [110]:
print(df.columns)

Index(['FIT101', 'LIT101', ' MV101', 'P101', 'P102', ' AIT201', 'AIT202',
       'AIT203', 'FIT201', 'Attack'],
      dtype='object')


In [111]:
df.corr()

FIT101    LIT101     MV101      P101      P102    AIT201    AIT202  \
FIT101   1.000000 -0.298459  0.954178  0.246174 -0.302655  0.015225 -0.110237   
LIT101  -0.298459  1.000000 -0.307484 -0.284165 -0.120232  0.064934  0.193150   
 MV101   0.954178 -0.307484  1.000000  0.254269 -0.290465  0.015892 -0.111924   
P101     0.246174 -0.284165  0.254269  1.000000  0.137654 -0.186919 -0.181848   
P102    -0.302655 -0.120232 -0.290465  0.137654  1.000000 -0.266006  0.020449   
 AIT201  0.015225  0.064934  0.015892 -0.186919 -0.266006  1.000000 -0.135132   
AIT202  -0.110237  0.193150 -0.111924 -0.181848  0.020449 -0.135132  1.000000   
AIT203   0.160823 -0.224773  0.174031  0.950163  0.103565 -0.100621 -0.183816   
FIT201   0.228909 -0.291868  0.237480  0.987933  0.200026 -0.207777 -0.179693   
Attack   0.092430  0.154976  0.079019 -0.035804  0.323887 -0.028984 -0.184318   

           AIT203    FIT201    Attack  
FIT101   0.160823  0.228909  0.092430  
LIT101  -0.224773 -0.291868  0.154976  
 MV101   0.174031  0.237480  0.079019  
P101     0.950163  0.987933 -0.035804  
P102     0.103565  0.200026  0.323887  
 AIT201 -0.100621 -0.207777 -0.028984  
AIT202  -0.183816 -0.179693 -0.184318  
AIT203   1.000000  0.957767 -0.012674  
FIT201   0.957767  1.000000 -0.019849  
Attack  -0.012674 -0.019849  1.000000

In [112]:
from sklearn.feature_selection import SelectKBest, chi2

In [113]:
X1 = df.iloc[:,0:-1]

In [114]:
Y1 = df.iloc[:,-1]

In [115]:
print(X1,Y1)

        FIT101    LIT101   MV101  P101  P102    AIT201    AIT202    AIT203  \
0     2.427057  522.8467       2     2     1  262.0161  8.396437  328.6337   
1     2.446274  522.8860       2     2     1  262.0161  8.396437  328.6337   
2     2.489191  522.8467       2     2     1  262.0161  8.394514  328.6337   
3     2.534350  522.9645       2     2     1  262.0161  8.394514  328.6337   
4     2.569260  523.4748       2     2     1  262.0161  8.394514  328.6337   
...        ...       ...     ...   ...   ...       ...       ...       ...   
9995  0.000000  810.6872       1     1     1  263.5222  8.439375  316.7906   
9996  0.000000  810.6479       1     1     1  263.5222  8.439375  316.7906   
9997  0.000000  810.8442       1     1     1  263.5222  8.439375  316.7906   
9998  0.000000  811.0012       1     1     1  263.5222  8.439375  316.7906   
9999  0.000000  810.6872       1     1     1  263.5222  8.439375  316.7906   

        FIT201  
0     2.445391  
1     2.445391  
2     2.4423

In [116]:
f = SelectKBest(score_func=chi2, k=5)

In [117]:
print(f)

SelectKBest(k=5, score_func=<function chi2 at 0x00000204555C8040>)


In [118]:
dir(SelectKBest)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_n_features',
 '_check_params',
 '_get_param_names',
 '_get_support_mask',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_validate_data',
 'fit',
 'fit_transform',
 'get_params',
 'get_support',
 'inverse_transform',
 'set_params',
 'transform']

In [119]:
f = f.fit(X1,Y1)

In [120]:
print(f)

SelectKBest(k=5, score_func=<function chi2 at 0x00000204555C8040>)


In [121]:
print(df.columns, f.scores_)

Index(['FIT101', 'LIT101', ' MV101', 'P101', 'P102', ' AIT201', 'AIT202',
       'AIT203', 'FIT201', 'Attack'],
      dtype='object') [5.37061804e+01 6.40661546e+03 7.28611338e+00 1.54030678e+00
 4.27040221e+01 9.11700145e-03 4.61726449e+00 1.45818719e-01
 2.79970895e+00]


In [122]:
m = f.get_support()

In [123]:
print(m)

[ True  True  True False  True False  True False False]


In [124]:
f = X1.columns[m]

In [125]:
print(f)

Index(['FIT101', 'LIT101', ' MV101', 'P102', 'AIT202'], dtype='object')


In [126]:
timesteps = 3

In [127]:
df_size = len(df)

In [128]:
print(df_size)

10000


In [129]:
df_resize = int(df_size//3)

In [130]:
print(df_resize)

3333


In [131]:
num_class = 1

In [132]:
X = df.iloc[:,:-1] 

In [133]:
print(X)

        FIT101    LIT101   MV101  P101  P102    AIT201    AIT202    AIT203  \
0     2.427057  522.8467       2     2     1  262.0161  8.396437  328.6337   
1     2.446274  522.8860       2     2     1  262.0161  8.396437  328.6337   
2     2.489191  522.8467       2     2     1  262.0161  8.394514  328.6337   
3     2.534350  522.9645       2     2     1  262.0161  8.394514  328.6337   
4     2.569260  523.4748       2     2     1  262.0161  8.394514  328.6337   
...        ...       ...     ...   ...   ...       ...       ...       ...   
9995  0.000000  810.6872       1     1     1  263.5222  8.439375  316.7906   
9996  0.000000  810.6479       1     1     1  263.5222  8.439375  316.7906   
9997  0.000000  810.8442       1     1     1  263.5222  8.439375  316.7906   
9998  0.000000  811.0012       1     1     1  263.5222  8.439375  316.7906   
9999  0.000000  810.6872       1     1     1  263.5222  8.439375  316.7906   

        FIT201  
0     2.445391  
1     2.445391  
2     2.4423

In [134]:
df_dim = len(X.columns)

In [135]:
print(df_dim)

9


In [136]:
df_trunc_size = df_resize * timesteps

In [137]:
print(df_trunc_size)

9999


In [138]:
Y = df.iloc[:,-1]

In [139]:
print(Y)

0       0
1       0
2       0
3       0
4       0
       ..
9995    0
9996    0
9997    0
9998    0
9999    0
Name: Attack, Length: 10000, dtype: int64


In [140]:
print(X,Y)

        FIT101    LIT101   MV101  P101  P102    AIT201    AIT202    AIT203  \
0     2.427057  522.8467       2     2     1  262.0161  8.396437  328.6337   
1     2.446274  522.8860       2     2     1  262.0161  8.396437  328.6337   
2     2.489191  522.8467       2     2     1  262.0161  8.394514  328.6337   
3     2.534350  522.9645       2     2     1  262.0161  8.394514  328.6337   
4     2.569260  523.4748       2     2     1  262.0161  8.394514  328.6337   
...        ...       ...     ...   ...   ...       ...       ...       ...   
9995  0.000000  810.6872       1     1     1  263.5222  8.439375  316.7906   
9996  0.000000  810.6479       1     1     1  263.5222  8.439375  316.7906   
9997  0.000000  810.8442       1     1     1  263.5222  8.439375  316.7906   
9998  0.000000  811.0012       1     1     1  263.5222  8.439375  316.7906   
9999  0.000000  810.6872       1     1     1  263.5222  8.439375  316.7906   

        FIT201  
0     2.445391  
1     2.445391  
2     2.4423

In [141]:
X = X.values
Y = Y.values

In [142]:
print(X,Y)

[[  2.427057 522.8467     2.       ...   8.396437 328.6337     2.445391]
 [  2.446274 522.886      2.       ...   8.396437 328.6337     2.445391]
 [  2.489191 522.8467     2.       ...   8.394514 328.6337     2.442316]
 ...
 [  0.       810.8442     1.       ...   8.439375 316.7906     0.      ]
 [  0.       811.0012     1.       ...   8.439375 316.7906     0.      ]
 [  0.       810.6872     1.       ...   8.439375 316.7906     0.      ]] [0 0 0 ... 0 0 0]


In [143]:
X = X[:df_trunc_size, :]

In [144]:
Y = Y[:df_trunc_size]

In [145]:
X.shape

(9999, 9)

In [146]:
Y.shape

(9999,)

In [147]:
X_shaped = X.reshape(df_resize, timesteps, df_dim)

In [148]:
X_shaped.shape

(3333, 3, 9)

In [149]:
Y_shaped = Y.reshape(df_resize,timesteps)

In [150]:
Y_shaped.shape

(3333, 3)

In [151]:
Y_shaped = Y_shaped[:,-1]

In [152]:
Y_shaped.shape

(3333,)

In [153]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_shaped, Y_shaped, test_size=0.2)

In [154]:
from keras.models import Sequential

In [155]:
from keras.layers import Dense, Dropout, SimpleRNN, LSTM, GRU

In [156]:
model = Sequential()

In [157]:
model.add(LSTM(8, input_shape=(timesteps, df_dim)))

In [158]:
model.add(Dropout(0.3))

In [159]:
model.add(Dense(num_class, activation = "sigmoid"))

In [160]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_7 (LSTM)                (None, 8)                 576       
_________________________________________________________________
dropout_6 (Dropout)          (None, 8)                 0         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 9         
Total params: 585
Trainable params: 585
Non-trainable params: 0
_________________________________________________________________


In [161]:
model.compile(loss = "binary_crossentropy", metrics=["accuracy"])

In [162]:
model.fit(X_train,Y_train, batch_size =10, epochs = 5)

Epoch 1/5
267/267 [==============================] - 2s 2ms/step - loss: 0.6042 - accuracy: 0.7321
Epoch 2/5
267/267 [==============================] - 0s 2ms/step - loss: 0.5942 - accuracy: 0.7133
Epoch 3/5
267/267 [==============================] - 0s 2ms/step - loss: 0.5941 - accuracy: 0.7103
Epoch 4/5
267/267 [==============================] - 0s 2ms/step - loss: 0.5829 - accuracy: 0.7133
Epoch 5/5
267/267 [==============================] - 0s 2ms/step - loss: 0.5710 - accuracy: 0.7155


In [163]:
model.evaluate(X_test,Y_test)

21/21 [==============================] - 0s 1ms/step - loss: 0.5509 - accuracy: 0.7331


[0.550855278968811, 0.7331334352493286]

In [164]:
pred = model.predict(X_test)

In [165]:
print(pred)

[[0.25935847]
 [0.2634676 ]
 [0.25930384]
 [0.25930384]
 [0.25983587]
 [0.25930384]
 [0.25930384]
 [0.25930458]
 [0.25930384]
 [0.37678212]
 [0.2644803 ]
 [0.25930384]
 [0.25930384]
 [0.25930387]
 [0.3763985 ]
 [0.25931174]
 [0.30175352]
 [0.25930852]
 [0.25930384]
 [0.3765808 ]
 [0.26154444]
 [0.25930384]
 [0.2593044 ]
 [0.3772534 ]
 [0.25930384]
 [0.26141843]
 [0.25930384]
 [0.26070887]
 [0.2809817 ]
 [0.25930384]
 [0.25930384]
 [0.3764739 ]
 [0.26114112]
 [0.263268  ]
 [0.25930384]
 [0.25930384]
 [0.25957075]
 [0.25930384]
 [0.29676276]
 [0.25930384]
 [0.25930977]
 [0.25930384]
 [0.25930387]
 [0.25930387]
 [0.2593039 ]
 [0.25930384]
 [0.2681947 ]
 [0.261535  ]
 [0.25930384]
 [0.25931144]
 [0.2640977 ]
 [0.25930595]
 [0.25930384]
 [0.25930387]
 [0.25930712]
 [0.25932035]
 [0.26095223]
 [0.37719202]
 [0.25930384]
 [0.25930384]
 [0.2593047 ]
 [0.2593044 ]
 [0.33621702]
 [0.37721953]
 [0.37749243]
 [0.25930387]
 [0.3766632 ]
 [0.25930384]
 [0.26162404]
 [0.25930384]
 [0.25930417]
 [0.33

In [166]:
pred = pred > 0.3


In [167]:
print(pred)

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 

In [168]:
pred = pred.reshape(pred.shape[0]*pred.shape[1])
print(pred)


[False False False False False False False False False  True False False
 False False  True False  True False False  True False False False  True
 False False False False False False False  True False False False False
 False False False False False False False False False False False False
 False False False False False False False False False  True False False
 False False  True  True  True False  True False False False False  True
  True False False False False False False False False False False False
 False False False  True False False False  True False False False False
 False False False False False False False False False  True False False
 False False False False False False False False  True False False False
 False False False False  True  True False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False Fa

In [171]:
len(pred)

667

In [175]:
actual = Y_test.reshape(Y_test.shape[0])
print(actual)


[1 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 1 0 1 1 0 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 1 1 0 1 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0 0 0
 0 0 0 0 0 1 1 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 1 1 1 0 1 0 0
 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 1 0 0 1 1 0
 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 1
 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 1 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 0 0
 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0
 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
 1 0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 1 1 0 1 1 0 0 0 0 0 1 0 0
 0 1 0 1 1 0 0 1 0 0 0 0 

In [176]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(actual, pred)


In [177]:
print(cm)

[[484   5]
 [120  58]]


In [178]:
pred = model.predict(X_test)
pred = pred > 0.3

pred = pred.reshape(pred.shape[0]*pred.shape[1])
print(pred)

actual = Y_test.reshape(Y_test.shape[0])
print(actual)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(actual, pred)
print(cm)
accuracy = (cm[0,0] + cm[1,1])/sum(sum(cm))
print(accuracy)


[False False False False False False False False False  True False False
 False False  True False  True False False  True False False False  True
 False False False False False False False  True False False False False
 False False False False False False False False False False False False
 False False False False False False False False False  True False False
 False False  True  True  True False  True False False False False  True
  True False False False False False False False False False False False
 False False False  True False False False  True False False False False
 False False False False False False False False False  True False False
 False False False False False False False False  True False False False
 False False False False  True  True False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False Fa